# aX Agent Studio Configuration

mcp:
  server_url: "http://localhost:8002"
  oauth_url: "http://localhost:8001"

monitors:
  timeout: null  # No timeout, wait forever
  reconnect_delay: 5
  max_retries: 3
  mark_read: false  # Keep messages unread so all agents see them
  startup_sweep: false  # DISABLED: MCP mode='unread' returns duplicates (TODO: investigate)
  startup_sweep_limit: 10  # Max messages to fetch on startup (0 = unlimited)

ollama:
  base_url: "http://localhost:11434/v1"
  default_model: "gpt-oss:latest"

dashboard:
  host: "127.0.0.1"
  port: 8000
